(finally) working caching for base image builds (#10)

diff --git a/.github/workflows/deploy-env.yml b/.github/workflows/deploy-env.yml
--- a/.github/workflows/deploy-env.yml
+++ b/.github/workflows/deploy-env.yml
@@ -42,24 +42,17 @@ jobs:
           aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_DEFAULT_REGION }}
 
-      - run: aws cloudformation deploy --template-file .cloudformation/base-ecr.yml --stack-name digitalvenue-${{ matrix.image }}-ecr --paramater-overrides Image=${{ matrix.image }}
+      - run: aws cloudformation deploy --template-file .cloudformation/base-ecr.yml --stack-name digitalvenue-${{ matrix.image }}-ecr --parameter-overrides Image=${{ matrix.image }}
 
       - uses: aws-actions/amazon-ecr-login@v2
 
       - uses: docker/setup-buildx-action@v3
 
-      # try pulling existing image to use as cache
-      - run: docker pull ${{ env.IMAGE }}:${{ env.VERSION }} || true
-
-      - uses: docker/build-push-action@v5
-        with:
-          context: .
-          file: docker/${{ matrix.image }}.Dockerfile
-          platforms: linux/arm64
-          push: true
-          tags: ${{ env.IMAGE }}:${{ env.VERSION }}
-          provenance: false
-          cache-from: ${{ env.IMAGE }}:${{ env.VERSION }}
+      - name: push ${{ env.IMAGE }}:${{ github.sha }}
+        run: docker buildx build --push --provenance false --platform linux/arm64 -t ${{ env.IMAGE }}:${{ github.sha }} --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from "type=registry,ref=${{ env.IMAGE }}:${{ env.VERSION }}-cache" --cache-to "mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${{ env.IMAGE }}:${{ env.VERSION }}-cache" --file docker/${{ matrix.image }}.Dockerfile .
+      # it's okay if this fails, b/c tags are immutable and it might already exist
+      - name: push ${{ env.IMAGE }}:${{ env.VERSION }}
+        run: docker buildx build --push --provenance false --platform linux/arm64 -t ${{ env.IMAGE }}:${{ env.VERSION }} --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from "type=registry,ref=${{ env.IMAGE }}:${{ env.VERSION }}-cache" --cache-to "mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${{ env.IMAGE }}:${{ env.VERSION }}-cache" --file docker/${{ matrix.image }}.Dockerfile . || true
 
   buildAndDeployInfra:
     runs-on: ubuntu-latest
@@ -79,10 +72,10 @@ jobs:
         run: aws cloudformation deploy --template-file .cloudformation/lambda-role.yml --stack-name ${{ env.STACK_PREFIX }}-lambda-role --capabilities CAPABILITY_IAM
 
       - name: deploy lambda api gateway
-        run: aws cloudformation deploy --template-file .cloudformation/lambda-gateway.yml --stack-name ${{ env.STACK_PREFIX }}-lambda-gateway
+        run: aws cloudformation deploy --template-file .cloudformation/lambda-gateway.yml --stack-name ${{ env.STACK_PREFIX }}-lambda-gateway --parameter-overrides Environment=${{ github.event.inputs.environment }}
 
   buildAndDeployLambdas:
-    needs: buildAndDeployInfra
+    needs: [baseImages, buildAndDeployInfra]
 
     strategy:
       matrix:
@@ -115,15 +108,7 @@ jobs:
 
       - uses: aws-actions/amazon-ecr-login@v2
 
-      - uses: docker/build-push-action@v5
-        with:
-          context: ${{ matrix.lambdas }}
-          file: ${{ matrix.lambdas }}/Dockerfile
-          platforms: linux/arm64
-          push: true
-          tags: ${{ env.LAMBDA_IMAGE }}
-          build-args: BUILDER=${{ env.BUILDER_IMAGE }} RUNNER=${{ env.RUNNER_IMAGE }}
-          provenance: false
+      - run: docker buildx build --push --provenance false --platform linux/arm64 -t ${{ env.LAMBDA_IMAGE }} --build-arg BUILDER=${{ env.BUILDER_IMAGE }} --build-arg RUNNER=${{ env.RUNNER_IMAGE }} ${{ matrix.lambdas }}
 
       - name: deploy ${{ matrix.lambdas }} lambda
         run: aws cloudformation deploy --template-file ${{ matrix.lambdas }}/lambda.yml --stack-name ${{ env.STACK_PREFIX }}-${{ matrix.lambdas}} --parameter-overrides LambdaTestECRStackName=digitalvenue-${{ matrix.lambdas}}-ecr LambdaRoleStackName=${{ env.STACK_PREFIX }}-lambda-role ImageVersion=${{ github.sha }}
